services:

 db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dksdlfduq2
      MYSQL_DATABASE: mobiusdb
    ports:
      - "3306:3306"
    volumes:
      - ./Mobius/mobius/mobiusdb.sql:/docker-entrypoint-initdb.d/mobiusdb.sql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/01-mysql-init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pdksdlfduq2"]
      interval: 10s
      timeout: 5s
      retries: 5

 node:
    image: "node:14.15.2"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - MQTT_HOST=mqtt
    volumes:
      - ./Mobius:/home/node/app
    ports:
      - "7579:7579"
      - "8081:8081"
    command: "node mobius"
    depends_on:
      db:
        condition: service_healthy

 mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./etc/mosquitto:/etc/mosquitto:ro
      - ./var/log/mosquitto:/var/log/mosquitto:rw
    depends_on:
      db:
        condition: service_healthy